#
# Module manifest for module 'Microsoft.Graph.DeviceManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 4/17/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.DeviceManagement.psm1'

# Version number of this module.
ModuleVersion = '2.27.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '4131557d-8635-4903-9cfd-d59ddef4a597'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.27.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.DeviceManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.DeviceManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Clear-MgDeviceManagementManagedDevice', 
               'Disable-MgDeviceManagementManagedDeviceLostMode', 
               'Find-MgDeviceManagementManagedDevice', 'Get-MgAdminEdge', 
               'Get-MgAdminEdgeInternetExplorerMode', 
               'Get-MgAdminEdgeInternetExplorerModeSiteList', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListCount', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSharedCookieCount', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Get-MgAdminEdgeInternetExplorerModeSiteListSiteCount', 
               'Get-MgDeviceManagement', 'Get-MgDeviceManagementDetectedApp', 
               'Get-MgDeviceManagementDetectedAppCount', 
               'Get-MgDeviceManagementDetectedAppManagedDevice', 
               'Get-MgDeviceManagementDetectedAppManagedDeviceCount', 
               'Get-MgDeviceManagementDeviceCategory', 
               'Get-MgDeviceManagementDeviceCategoryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicy', 
               'Get-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Get-MgDeviceManagementDeviceCompliancePolicyAssignmentCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatusCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Get-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfigurationCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Get-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingStateCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatusCount', 
               'Get-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Get-MgDeviceManagementDeviceConfiguration', 
               'Get-MgDeviceManagementDeviceConfigurationAssignment', 
               'Get-MgDeviceManagementDeviceConfigurationAssignmentCount', 
               'Get-MgDeviceManagementDeviceConfigurationCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummaryCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatusCount', 
               'Get-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatusCount', 
               'Get-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Get-MgDeviceManagementManagedDevice', 
               'Get-MgDeviceManagementManagedDeviceCategory', 
               'Get-MgDeviceManagementManagedDeviceCategoryByRef', 
               'Get-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Get-MgDeviceManagementManagedDeviceCompliancePolicyStateCount', 
               'Get-MgDeviceManagementManagedDeviceConfigurationState', 
               'Get-MgDeviceManagementManagedDeviceConfigurationStateCount', 
               'Get-MgDeviceManagementManagedDeviceCount', 
               'Get-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Get-MgDeviceManagementManagedDeviceLogCollectionRequestCount', 
               'Get-MgDeviceManagementManagedDeviceOverview', 
               'Get-MgDeviceManagementManagedDeviceUser', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequestCount', 
               'Get-MgDeviceManagementMobileAppTroubleshootingEventCount', 
               'Get-MgDeviceManagementNotificationMessageTemplate', 
               'Get-MgDeviceManagementNotificationMessageTemplateCount', 
               'Get-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Get-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessageCount', 
               'Get-MgDeviceManagementSoftwareUpdateStatusSummary', 
               'Get-MgDeviceManagementTroubleshootingEvent', 
               'Get-MgDeviceManagementTroubleshootingEventCount', 
               'Get-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Get-MgDeviceManagementWindowsInformationProtectionAppLearningSummaryCount', 
               'Get-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Get-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummaryCount', 
               'Get-MgDeviceManagementWindowsMalwareInformation', 
               'Get-MgDeviceManagementWindowsMalwareInformationCount', 
               'Get-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Get-MgDeviceManagementWindowsMalwareInformationDeviceMalwareStateCount', 
               'Invoke-MgCleanDeviceManagementManagedDeviceWindowsDevice', 
               'Invoke-MgDownDeviceManagementManagedDeviceShut', 
               'Invoke-MgLogoutDeviceManagementManagedDeviceSharedAppleDeviceActiveUser', 
               'Invoke-MgRetireDeviceManagementManagedDevice', 
               'Invoke-MgScanDeviceManagementManagedDeviceWindowsDefender', 
               'Invoke-MgScheduleDeviceManagementDeviceCompliancePolicyActionForRule', 
               'Lock-MgDeviceManagementManagedDeviceRemote', 
               'New-MgAdminEdgeInternetExplorerModeSiteList', 
               'New-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'New-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'New-MgDeviceManagementDetectedApp', 
               'New-MgDeviceManagementDeviceCategory', 
               'New-MgDeviceManagementDeviceCompliancePolicy', 
               'New-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'New-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'New-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'New-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'New-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'New-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'New-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'New-MgDeviceManagementDeviceConfiguration', 
               'New-MgDeviceManagementDeviceConfigurationAssignment', 
               'New-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'New-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'New-MgDeviceManagementDeviceConfigurationUserStatus', 
               'New-MgDeviceManagementManagedDevice', 
               'New-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'New-MgDeviceManagementManagedDeviceConfigurationState', 
               'New-MgDeviceManagementManagedDeviceLogCollectionRequestDownloadUrl', 
               'New-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'New-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'New-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'New-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequestDownloadUrl', 
               'New-MgDeviceManagementNotificationMessageTemplate', 
               'New-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'New-MgDeviceManagementTroubleshootingEvent', 
               'New-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'New-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'New-MgDeviceManagementWindowsMalwareInformation', 
               'New-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Publish-MgAdminEdgeInternetExplorerModeSiteList', 
               'Remove-MgAdminEdge', 'Remove-MgAdminEdgeInternetExplorerMode', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteList', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Remove-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Remove-MgDeviceManagementDetectedApp', 
               'Remove-MgDeviceManagementDeviceCategory', 
               'Remove-MgDeviceManagementDeviceCompliancePolicy', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Remove-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Remove-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Remove-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Remove-MgDeviceManagementDeviceConfiguration', 
               'Remove-MgDeviceManagementDeviceConfigurationAssignment', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Remove-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Remove-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Remove-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Remove-MgDeviceManagementManagedDevice', 
               'Remove-MgDeviceManagementManagedDeviceCategory', 
               'Remove-MgDeviceManagementManagedDeviceCategoryByRef', 
               'Remove-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Remove-MgDeviceManagementManagedDeviceConfigurationState', 
               'Remove-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Remove-MgDeviceManagementManagedDeviceUserFromSharedAppleDevice', 
               'Remove-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Remove-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Remove-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Remove-MgDeviceManagementNotificationMessageTemplate', 
               'Remove-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Remove-MgDeviceManagementTroubleshootingEvent', 
               'Remove-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Remove-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Remove-MgDeviceManagementWindowsMalwareInformation', 
               'Remove-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Request-MgDeviceManagementManagedDeviceRemoteAssistance', 
               'Reset-MgDeviceManagementManagedDevicePasscode', 
               'Restart-MgDeviceManagementManagedDeviceNow', 
               'Restore-MgDeviceManagementManagedDevicePasscode', 
               'Send-MgDeviceManagementNotificationMessageTemplateTestMessage', 
               'Set-MgDeviceManagementDeviceCompliancePolicy', 
               'Set-MgDeviceManagementDeviceConfiguration', 
               'Set-MgDeviceManagementManagedDeviceCategoryByRef', 
               'Skip-MgDeviceManagementManagedDeviceActivationLock', 
               'Sync-MgDeviceManagementManagedDevice', 'Update-MgAdminEdge', 
               'Update-MgAdminEdgeInternetExplorerMode', 
               'Update-MgAdminEdgeInternetExplorerModeSiteList', 
               'Update-MgAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Update-MgAdminEdgeInternetExplorerModeSiteListSite', 
               'Update-MgDeviceManagement', 'Update-MgDeviceManagementDetectedApp', 
               'Update-MgDeviceManagementDeviceCategory', 
               'Update-MgDeviceManagementDeviceCompliancePolicy', 
               'Update-MgDeviceManagementDeviceCompliancePolicyAssignment', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Update-MgDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Update-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Update-MgDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Update-MgDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Update-MgDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Update-MgDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Update-MgDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Update-MgDeviceManagementDeviceConfiguration', 
               'Update-MgDeviceManagementDeviceConfigurationAssignment', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStatus', 
               'Update-MgDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Update-MgDeviceManagementDeviceConfigurationUserStatus', 
               'Update-MgDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Update-MgDeviceManagementManagedDevice', 
               'Update-MgDeviceManagementManagedDeviceCategory', 
               'Update-MgDeviceManagementManagedDeviceCompliancePolicyState', 
               'Update-MgDeviceManagementManagedDeviceConfigurationState', 
               'Update-MgDeviceManagementManagedDeviceLogCollectionRequest', 
               'Update-MgDeviceManagementManagedDeviceWindowsDeviceAccount', 
               'Update-MgDeviceManagementManagedDeviceWindowsProtectionState', 
               'Update-MgDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Update-MgDeviceManagementMobileAppTroubleshootingEvent', 
               'Update-MgDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Update-MgDeviceManagementNotificationMessageTemplate', 
               'Update-MgDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Update-MgDeviceManagementTroubleshootingEvent', 
               'Update-MgDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Update-MgDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Update-MgDeviceManagementWindowsMalwareInformation', 
               'Update-MgDeviceManagementWindowsMalwareInformationDeviceMalwareState'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKgYJKoZIhvcNAQcCoIIoGzCCKBcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAVAklYZXFpRGSS
# O5YndpZI6fsPCvzgXwLOBBP7hYEoGqCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIF4jpaM/izFJVhZfh0vaZo30
# OE0wdbBjUgfKHbD+yv6+MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEArZZWQ7IrVtGvxowzVipu+EiOq9HKwlTNBL0MMPMhSm0hNO+n28/sdYlR
# xXo9HuKxhukHNRNlry1cW3fpf5hbVCHKaRA5SiOetoHwrlEsxl/vBIqoTv3KK2pQ
# 0kXCwRaBCGSNIbMu4TGezLK6OJzw6z111abbuSNtPLAVxERePYUUsQOf8DGVJePF
# XHRNlaxcsN8uQT+iN3CdvRmGIrjNGU33zftPRp9wi3RIztUQup/COxMDklOsk2tu
# nfZ1sXbnLnQAJA8MjOsMWTqQ/s6/4MYxVR7lvnXGC1vSHMZnjn2EJf9DkTAyqkR6
# lZEFtXmnyiTx8u4SgH/3DPWjuSkGi6GCF5QwgheQBgorBgEEAYI3AwMBMYIXgDCC
# F3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCA9SW6Qn6ip1llFHPgGpLD/pFUlWk5Pu1L5swx7vrV1xAIGZ/fhHUew
# GBMyMDI1MDQxNzEzNDMzNS44MTFaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046OEQwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHqMIIHIDCCBQigAwIBAgITMwAAAg0Nd757No9/4wABAAACDTANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNTAxMzAxOTQz
# MDFaFw0yNjA0MjIxOTQzMDFaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046OEQwMC0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQCxf6gH3fH3wgmFN5TV8zRF/N0TJguWUYCrQZPUmwA+
# QhSySNp7kiGmFZd4b5zsAfN0Wh+PzIJvYsVMgVCaZcbVr/DJBfexwnQfc+fgIjOi
# AzYSjg7EtSOdWoLk81b/mGiGIBC++fLcSAzbZO3KtW4PRKOSsdD/5eRdtNca/Ed4
# EAcUT32zAGS9Sq//4kDT92KEzRNXJj8z3NDL4oGGzCQMvA83tQG5mrnepxF0OsNf
# KKHYHMqjyOEP5pTgKfT5XMfz0sEG6ARAjlXJ79SG/joeuHh8TqC+cJMry9wB7ZLr
# dMAFy8rHN3W1+kkpw47Ko+9ize2ble+P5jMaqufK033Bu+2FXVSKphil2j0qBUWp
# n5vBtf2W+gsVqydA+eseBHfYxcDZ4+5oRoyDAg0tW9f79vOAv91P4bTzG+BZPBbD
# MzSDwmj8ASKDlVwruTeF1em7NWiedWAB+29gFH/c/NN1uTQLvwGDIOw1DcLnCD0V
# XNL7mOvifYvNWugTAHcMFLVlA1jeOH35E/IW9qcKKqrah7LyJax/6M5UHswQugGg
# LriiMNEvz3IqW+AiIJ097iYzMGzsDqbLSUztIjDEt9xfIHHUs/p3j9Bkr2bPP1v4
# z8vp/45Ck3mfFbW2F0EtjOCnGPMrJNjjGhEG9zAK1105Bg2kJ7Rn8WTWO5IbD/rD
# tQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFBWXjpDmDgNrTsISj26SjU1/YMOAMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQAcH8gT42wVQ8GQZ+MHIXNJ+d4dQn0+vPG/
# AdFvTxk/tvOOkA2i7hnoEOEFcSbzS5EdIVCMi5Y5EiWT8hEJkztdeq5hXtUWsPY+
# 2lYSU9HdhKDfRDfjwVZ9kfCthrLRC3jw9Fah5MAGI9MHSETo9r7+cux8AUqQ3hma
# M2jmTNWvrFOLbO01B1ciNGbvE2xK+rbzBBh/uWd3k30pau6Lp0azg7rDYGMGv8jW
# otILfpKMBeCQoufMsI/gzxo4+k9dqYBkAwMk7h1hf23ycb5WngSMQV/Uxl3Sxbg+
# 64KK6GCsTSG6z7zNTgbL69PMGfwV2cnawY95Iy2cgJ6cbMORRUcYzvsuUd8oEQ87
# cW4XqqBLrheewJjROT6YyWrQ2oQ+jzGK2WJoGNnfanmNfqQnVKpi320onag95LMF
# jj8BwrflYsO9kEOiy7I5UngPBmF+RHSCv2hFSr8nK7gtuiy9SUOKP6FbQOzyMRvJ
# 3UxsmrH38477XzETb/tZLAj10TdYFfkjkFeFjlb3iMTSs/VrJSF0r0vON/oxZqKC
# Y8WZez+uQP0Try0QQ9wRp5D2FYJ8E1uIX/LvwuFkBdWf7X7qlb+pzdvPpSAcaCgB
# IWTlMn2bWgkU5uPzxRPHh/0u+FI7/eRCZGbLM2qnn3yXQvO/h9wQm8pIABRAvoda
# iV0bVmHbETCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNN
# MIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjhEMDAtMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQB7
# LCwoj6G3nQ7Oxhl/pfne4yATPaCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA66rwwjAiGA8yMDI1MDQxNzAzMTUx
# NFoYDzIwMjUwNDE4MDMxNTE0WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDrqvDC
# AgEAMAcCAQACAhL6MAcCAQACAhI3MAoCBQDrrEJCAgEAMDYGCisGAQQBhFkKBAIx
# KDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZI
# hvcNAQELBQADggEBABkG9no/RyhcXXDg5xZy0s7sYZ0Gt4wE8psk/w6BT0nulw3f
# PZSbuQJwTiYxE3h4biZee5MqKYJxbYzTm9x/wDNBbgq4J38FBJCtqg3yoIxnWa2P
# +H+1uxkvZp8Jfor3cRKZzzSnAD8503aDcpht/lynj+h3w3sm1nhrChTKb2Wh7hvT
# 0QOWgXG6Ojr5L2C9f1hMviUEjNjUCJnVndgmPUUrxeSnnoJiuIiDqUornujqZBFm
# TjBDM4eotU11UFKdGy+WqQp94+XGT2vOJvurRJlIjRhDDt8M7qiLUXD1eMxL+Bfl
# IoDP2QjzcGySCuVH3P5B0W1ghELr6ynfLEJ384YxggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAg0Nd757No9/4wABAAACDTAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCCj8290TNIHFvbnQWJQDQ7tK+tsiapmj+YOoxkBatU7JjCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIGPqB5TsJGqI8OuknBKtSvb0Ffq6
# w5NSs5veTVwka/hAMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAINDXe+ezaPf+MAAQAAAg0wIgQgzRDp21SUjF66pZaMhbS8WObuAz1g
# zOv7Er/lcCY8+n0wDQYJKoZIhvcNAQELBQAEggIAFtK1nUyqUz++xHSX53/C5DoL
# NUwMEfVd5vV9imkAXNiiA2eU13LbSxwaHU7/LiIy48kXAh3EL6f8PHrnU/Yh/7Ge
# fu9LAAEp5Ag+z7vxtzcylYoqv/LkrgOkDCnDN/C/xN0AModv6AZltVQ+BKrUnNUD
# kirUujQSwEA0pcOZKQ/NXnRKPEf5QAyFZroxwjN7dedxT7jtYucYmpBuxvw/p0jK
# ysC2SNtkzFPoT3vWyHDJOxPMd62tIRpu5EY8jNLjBS+Z4hO+aTpWjCqcgMvYNCp9
# NRMmjp/OVznTw7PD6RIJUiOZrQwlJlhGLQiKg5JotFr5K/k/SNgmwMJNEcWbcTSd
# nNbZzZNKuWzfyFzWsVq6nEcbAaQlm7gxbWcGPivKJR42HU6qhS/ZOQQrwe2jiXbL
# MdPGgFgj+Ho1oxW0QqWQPG5uG5qv2/dz9pxiXCtcNaz+SsclmgB/pic92UW+G5Wo
# Asr2I8zWc5W1jLdZDnYJOWRXJ1bXmRWVPr0X+ENR0JpRkEVvVpUWhwQxy3rkzTHl
# suERdSAQtwLDxGzuufMYzP5qVlDz2GwACToMO7hLtEA38+DMdK/2Iq9ZFwQbDnzD
# gcoUf56kUKuwWUze6es8oXaDZuXHCkIl+R4tLM7liZrqrHOWRrOmOJxacFFdJLem
# 2YwN2+soxBe4z+MJx5M=
# SIG # End signature block
