#
# Module manifest for module 'Microsoft.Graph.Education'
#
# Generated by: Microsoft Corporation
#
# Generated on: 4/17/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Education.psm1'

# Version number of this module.
ModuleVersion = '2.27.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'c413b855-1538-4f43-80a9-cb453e059e8a'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.27.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Education.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Education.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgEducationClass', 'Get-MgEducationClassAssignment', 
               'Get-MgEducationClassAssignmentCategory', 
               'Get-MgEducationClassAssignmentCategoryByRef', 
               'Get-MgEducationClassAssignmentCategoryCount', 
               'Get-MgEducationClassAssignmentCategoryDelta', 
               'Get-MgEducationClassAssignmentCount', 
               'Get-MgEducationClassAssignmentDefault', 
               'Get-MgEducationClassAssignmentDelta', 
               'Get-MgEducationClassAssignmentGradingCategory', 
               'Get-MgEducationClassAssignmentResource', 
               'Get-MgEducationClassAssignmentResourceCount', 
               'Get-MgEducationClassAssignmentRubric', 
               'Get-MgEducationClassAssignmentRubricByRef', 
               'Get-MgEducationClassAssignmentSetting', 
               'Get-MgEducationClassAssignmentSettingGradingCategory', 
               'Get-MgEducationClassAssignmentSettingGradingCategoryCount', 
               'Get-MgEducationClassAssignmentSubmission', 
               'Get-MgEducationClassAssignmentSubmissionCount', 
               'Get-MgEducationClassAssignmentSubmissionOutcome', 
               'Get-MgEducationClassAssignmentSubmissionOutcomeCount', 
               'Get-MgEducationClassAssignmentSubmissionResource', 
               'Get-MgEducationClassAssignmentSubmissionResourceCount', 
               'Get-MgEducationClassAssignmentSubmissionSubmittedResource', 
               'Get-MgEducationClassAssignmentSubmissionSubmittedResourceCount', 
               'Get-MgEducationClassCount', 'Get-MgEducationClassDelta', 
               'Get-MgEducationClassGroup', 
               'Get-MgEducationClassGroupServiceProvisioningError', 
               'Get-MgEducationClassGroupServiceProvisioningErrorCount', 
               'Get-MgEducationClassMember', 'Get-MgEducationClassMemberByRef', 
               'Get-MgEducationClassMemberCount', 'Get-MgEducationClassModule', 
               'Get-MgEducationClassModuleCount', 
               'Get-MgEducationClassModuleResource', 
               'Get-MgEducationClassModuleResourceCount', 
               'Get-MgEducationClassSchool', 'Get-MgEducationClassSchoolCount', 
               'Get-MgEducationClassTeacher', 'Get-MgEducationClassTeacherByRef', 
               'Get-MgEducationClassTeacherCount', 'Get-MgEducationMe', 
               'Get-MgEducationMeAssignment', 
               'Get-MgEducationMeAssignmentCategory', 
               'Get-MgEducationMeAssignmentCategoryByRef', 
               'Get-MgEducationMeAssignmentCategoryCount', 
               'Get-MgEducationMeAssignmentCategoryDelta', 
               'Get-MgEducationMeAssignmentCount', 
               'Get-MgEducationMeAssignmentDelta', 
               'Get-MgEducationMeAssignmentGradingCategory', 
               'Get-MgEducationMeAssignmentResource', 
               'Get-MgEducationMeAssignmentResourceCount', 
               'Get-MgEducationMeAssignmentRubric', 
               'Get-MgEducationMeAssignmentRubricByRef', 
               'Get-MgEducationMeAssignmentSubmission', 
               'Get-MgEducationMeAssignmentSubmissionCount', 
               'Get-MgEducationMeAssignmentSubmissionOutcome', 
               'Get-MgEducationMeAssignmentSubmissionOutcomeCount', 
               'Get-MgEducationMeAssignmentSubmissionResource', 
               'Get-MgEducationMeAssignmentSubmissionResourceCount', 
               'Get-MgEducationMeAssignmentSubmissionSubmittedResource', 
               'Get-MgEducationMeAssignmentSubmissionSubmittedResourceCount', 
               'Get-MgEducationMeClass', 'Get-MgEducationMeClassCount', 
               'Get-MgEducationMeRubric', 'Get-MgEducationMeRubricCount', 
               'Get-MgEducationMeSchool', 'Get-MgEducationMeSchoolCount', 
               'Get-MgEducationMeTaughtClass', 'Get-MgEducationMeTaughtClassCount', 
               'Get-MgEducationMeUser', 'Get-MgEducationMeUserMailboxSetting', 
               'Get-MgEducationMeUserServiceProvisioningError', 
               'Get-MgEducationMeUserServiceProvisioningErrorCount', 
               'Get-MgEducationRoot', 'Get-MgEducationSchool', 
               'Get-MgEducationSchoolAdministrativeUnit', 
               'Get-MgEducationSchoolClass', 'Get-MgEducationSchoolClassByRef', 
               'Get-MgEducationSchoolClassCount', 'Get-MgEducationSchoolCount', 
               'Get-MgEducationSchoolDelta', 'Get-MgEducationSchoolUser', 
               'Get-MgEducationSchoolUserByRef', 'Get-MgEducationSchoolUserCount', 
               'Get-MgEducationUser', 'Get-MgEducationUserAssignment', 
               'Get-MgEducationUserAssignmentCategory', 
               'Get-MgEducationUserAssignmentCategoryByRef', 
               'Get-MgEducationUserAssignmentCategoryCount', 
               'Get-MgEducationUserAssignmentCategoryDelta', 
               'Get-MgEducationUserAssignmentCount', 
               'Get-MgEducationUserAssignmentDelta', 
               'Get-MgEducationUserAssignmentGradingCategory', 
               'Get-MgEducationUserAssignmentResource', 
               'Get-MgEducationUserAssignmentResourceCount', 
               'Get-MgEducationUserAssignmentRubric', 
               'Get-MgEducationUserAssignmentRubricByRef', 
               'Get-MgEducationUserAssignmentSubmission', 
               'Get-MgEducationUserAssignmentSubmissionCount', 
               'Get-MgEducationUserAssignmentSubmissionOutcome', 
               'Get-MgEducationUserAssignmentSubmissionOutcomeCount', 
               'Get-MgEducationUserAssignmentSubmissionResource', 
               'Get-MgEducationUserAssignmentSubmissionResourceCount', 
               'Get-MgEducationUserAssignmentSubmissionSubmittedResource', 
               'Get-MgEducationUserAssignmentSubmissionSubmittedResourceCount', 
               'Get-MgEducationUserClass', 'Get-MgEducationUserClassCount', 
               'Get-MgEducationUserCount', 'Get-MgEducationUserDelta', 
               'Get-MgEducationUserMailboxSetting', 'Get-MgEducationUserRubric', 
               'Get-MgEducationUserRubricCount', 'Get-MgEducationUserSchool', 
               'Get-MgEducationUserSchoolCount', 
               'Get-MgEducationUserServiceProvisioningError', 
               'Get-MgEducationUserServiceProvisioningErrorCount', 
               'Get-MgEducationUserTaughtClass', 
               'Get-MgEducationUserTaughtClassCount', 
               'Initialize-MgEducationClassAssignment', 
               'Initialize-MgEducationMeAssignment', 
               'Initialize-MgEducationUserAssignment', 
               'Invoke-MgDeactivateEducationClassAssignment', 
               'Invoke-MgDeactivateEducationMeAssignment', 
               'Invoke-MgDeactivateEducationUserAssignment', 
               'Invoke-MgExcuseEducationClassAssignmentSubmission', 
               'Invoke-MgExcuseEducationMeAssignmentSubmission', 
               'Invoke-MgExcuseEducationUserAssignmentSubmission', 
               'Invoke-MgPinEducationClassModule', 
               'Invoke-MgReassignEducationClassAssignmentSubmission', 
               'Invoke-MgReassignEducationMeAssignmentSubmission', 
               'Invoke-MgReassignEducationUserAssignmentSubmission', 
               'Invoke-MgReturnEducationClassAssignmentSubmission', 
               'Invoke-MgReturnEducationMeAssignmentSubmission', 
               'Invoke-MgReturnEducationUserAssignmentSubmission', 
               'Invoke-MgUnpinEducationClassModule', 
               'Invoke-MgUnsubmitEducationClassAssignmentSubmission', 
               'Invoke-MgUnsubmitEducationMeAssignmentSubmission', 
               'Invoke-MgUnsubmitEducationUserAssignmentSubmission', 
               'New-MgEducationClass', 'New-MgEducationClassAssignment', 
               'New-MgEducationClassAssignmentCategory', 
               'New-MgEducationClassAssignmentCategoryByRef', 
               'New-MgEducationClassAssignmentResource', 
               'New-MgEducationClassAssignmentSettingGradingCategory', 
               'New-MgEducationClassAssignmentSubmission', 
               'New-MgEducationClassAssignmentSubmissionOutcome', 
               'New-MgEducationClassAssignmentSubmissionResource', 
               'New-MgEducationClassAssignmentSubmissionSubmittedResource', 
               'New-MgEducationClassMemberByRef', 'New-MgEducationClassModule', 
               'New-MgEducationClassModuleResource', 
               'New-MgEducationClassTeacherByRef', 'New-MgEducationMeAssignment', 
               'New-MgEducationMeAssignmentCategory', 
               'New-MgEducationMeAssignmentCategoryByRef', 
               'New-MgEducationMeAssignmentResource', 
               'New-MgEducationMeAssignmentSubmission', 
               'New-MgEducationMeAssignmentSubmissionOutcome', 
               'New-MgEducationMeAssignmentSubmissionResource', 
               'New-MgEducationMeAssignmentSubmissionSubmittedResource', 
               'New-MgEducationMeRubric', 'New-MgEducationSchool', 
               'New-MgEducationSchoolClassByRef', 'New-MgEducationSchoolUserByRef', 
               'New-MgEducationUser', 'New-MgEducationUserAssignment', 
               'New-MgEducationUserAssignmentCategory', 
               'New-MgEducationUserAssignmentCategoryByRef', 
               'New-MgEducationUserAssignmentResource', 
               'New-MgEducationUserAssignmentSubmission', 
               'New-MgEducationUserAssignmentSubmissionOutcome', 
               'New-MgEducationUserAssignmentSubmissionResource', 
               'New-MgEducationUserAssignmentSubmissionSubmittedResource', 
               'New-MgEducationUserRubric', 'Publish-MgEducationClassAssignment', 
               'Publish-MgEducationClassModule', 'Publish-MgEducationMeAssignment', 
               'Publish-MgEducationUserAssignment', 'Remove-MgEducationClass', 
               'Remove-MgEducationClassAssignment', 
               'Remove-MgEducationClassAssignmentCategory', 
               'Remove-MgEducationClassAssignmentCategoryEducationCategoryByRef', 
               'Remove-MgEducationClassAssignmentDefault', 
               'Remove-MgEducationClassAssignmentResource', 
               'Remove-MgEducationClassAssignmentRubric', 
               'Remove-MgEducationClassAssignmentRubricByRef', 
               'Remove-MgEducationClassAssignmentSetting', 
               'Remove-MgEducationClassAssignmentSettingGradingCategory', 
               'Remove-MgEducationClassAssignmentSubmission', 
               'Remove-MgEducationClassAssignmentSubmissionOutcome', 
               'Remove-MgEducationClassAssignmentSubmissionResource', 
               'Remove-MgEducationClassAssignmentSubmissionSubmittedResource', 
               'Remove-MgEducationClassMemberEducationUserByRef', 
               'Remove-MgEducationClassModule', 
               'Remove-MgEducationClassModuleResource', 
               'Remove-MgEducationClassTeacherEducationUserByRef', 
               'Remove-MgEducationMe', 'Remove-MgEducationMeAssignment', 
               'Remove-MgEducationMeAssignmentCategoryEducationCategoryByRef', 
               'Remove-MgEducationMeAssignmentResource', 
               'Remove-MgEducationMeAssignmentRubric', 
               'Remove-MgEducationMeAssignmentRubricByRef', 
               'Remove-MgEducationMeAssignmentSubmission', 
               'Remove-MgEducationMeAssignmentSubmissionOutcome', 
               'Remove-MgEducationMeAssignmentSubmissionResource', 
               'Remove-MgEducationMeAssignmentSubmissionSubmittedResource', 
               'Remove-MgEducationMeRubric', 'Remove-MgEducationSchool', 
               'Remove-MgEducationSchoolClassEducationClassByRef', 
               'Remove-MgEducationSchoolUserEducationUserByRef', 
               'Remove-MgEducationUser', 'Remove-MgEducationUserAssignment', 
               'Remove-MgEducationUserAssignmentCategoryEducationCategoryByRef', 
               'Remove-MgEducationUserAssignmentResource', 
               'Remove-MgEducationUserAssignmentRubric', 
               'Remove-MgEducationUserAssignmentRubricByRef', 
               'Remove-MgEducationUserAssignmentSubmission', 
               'Remove-MgEducationUserAssignmentSubmissionOutcome', 
               'Remove-MgEducationUserAssignmentSubmissionResource', 
               'Remove-MgEducationUserAssignmentSubmissionSubmittedResource', 
               'Remove-MgEducationUserRubric', 
               'Set-MgEducationClassAssignmentRubricByRef', 
               'Set-MgEducationClassAssignmentSubmissionUpResourceFolder', 
               'Set-MgEducationClassAssignmentUpFeedbackResourceFolder', 
               'Set-MgEducationClassAssignmentUpResourceFolder', 
               'Set-MgEducationClassModuleUpResourceFolder', 
               'Set-MgEducationMeAssignmentRubricByRef', 
               'Set-MgEducationMeAssignmentSubmissionUpResourceFolder', 
               'Set-MgEducationMeAssignmentUpFeedbackResourceFolder', 
               'Set-MgEducationMeAssignmentUpResourceFolder', 
               'Set-MgEducationUserAssignmentRubricByRef', 
               'Set-MgEducationUserAssignmentSubmissionUpResourceFolder', 
               'Set-MgEducationUserAssignmentUpFeedbackResourceFolder', 
               'Set-MgEducationUserAssignmentUpResourceFolder', 
               'Submit-MgEducationClassAssignmentSubmission', 
               'Submit-MgEducationMeAssignmentSubmission', 
               'Submit-MgEducationUserAssignmentSubmission', 
               'Update-MgEducationClass', 'Update-MgEducationClassAssignment', 
               'Update-MgEducationClassAssignmentCategory', 
               'Update-MgEducationClassAssignmentDefault', 
               'Update-MgEducationClassAssignmentResource', 
               'Update-MgEducationClassAssignmentRubric', 
               'Update-MgEducationClassAssignmentSetting', 
               'Update-MgEducationClassAssignmentSettingGradingCategory', 
               'Update-MgEducationClassAssignmentSubmission', 
               'Update-MgEducationClassAssignmentSubmissionOutcome', 
               'Update-MgEducationClassAssignmentSubmissionResource', 
               'Update-MgEducationClassAssignmentSubmissionSubmittedResource', 
               'Update-MgEducationClassModule', 
               'Update-MgEducationClassModuleResource', 'Update-MgEducationMe', 
               'Update-MgEducationMeAssignment', 
               'Update-MgEducationMeAssignmentResource', 
               'Update-MgEducationMeAssignmentRubric', 
               'Update-MgEducationMeAssignmentSubmission', 
               'Update-MgEducationMeAssignmentSubmissionOutcome', 
               'Update-MgEducationMeAssignmentSubmissionResource', 
               'Update-MgEducationMeAssignmentSubmissionSubmittedResource', 
               'Update-MgEducationMeRubric', 
               'Update-MgEducationMeUserMailboxSetting', 'Update-MgEducationRoot', 
               'Update-MgEducationSchool', 
               'Update-MgEducationSchoolAdministrativeUnit', 
               'Update-MgEducationUser', 'Update-MgEducationUserAssignment', 
               'Update-MgEducationUserAssignmentResource', 
               'Update-MgEducationUserAssignmentRubric', 
               'Update-MgEducationUserAssignmentSubmission', 
               'Update-MgEducationUserAssignmentSubmissionOutcome', 
               'Update-MgEducationUserAssignmentSubmissionResource', 
               'Update-MgEducationUserAssignmentSubmissionSubmittedResource', 
               'Update-MgEducationUserMailboxSetting', 
               'Update-MgEducationUserRubric'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgEducationClassAssignmentCategoryByRef', 
               'Remove-MgEducationClassMemberByRef', 
               'Remove-MgEducationClassTeacherByRef', 
               'Remove-MgEducationMeAssignmentCategoryByRef', 
               'Remove-MgEducationSchoolClassByRef', 
               'Remove-MgEducationSchoolUserByRef', 
               'Remove-MgEducationUserAssignmentCategoryByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoRgYJKoZIhvcNAQcCoIIoNzCCKDMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDqthCG49Tj5s2B
# E7psBGo/+ELCh8BOwmT5x654gGzuWKCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIH/7BhQEI4MkCSRvpcHTEM4d
# oDHuearuagrugU6+A9BGMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEADJjhjNSX+rTRblXCEbZBg2EipqUXprC3C3XftVFlGypgjBp6A1LVw03m
# uWGh9NTzl3MsGlGtMl/7PNhBDR9PLL6Daks1XTF6NFFbsINgvNA3oANiy7JAyvw2
# 1YgPiTpCHaAP6FuAD+0Qm2JQ+YCdCZVxMJa0nZ73mPa3P7irIHQyxoCAv+zJsM3b
# itCMO1JPdPN8qAAAsVaROCD2/Mc5rUktoHaDViGU6yQPGXrqL4oiVU4keL8zaCxM
# NWtV1xOA9d3zG4Js3YPSoJQSWGqVWaNzPMeUiaC3JpkZsBpSYU4xNnvMhpKmBRfA
# unx4ddPqFMxqxNfPyFZhewKKeFMCvKGCF7AwghesBgorBgEEAYI3AwMBMYIXnDCC
# F5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCDrusq4F1KBBOLqUilf2y0GNcAXWZSNmcUMymhMT6H57gIGZ+0jpYvZ
# GBMyMDI1MDQxNzEzNDM1My45NTVaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo2RjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB/Bigr8xpWoc6AAEAAAH8MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzExNFoXDTI1MTAyMjE4MzExNFowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjZGMUEt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAp1DAKLxpbQcPVYPHlJHy
# W7W5lBZjJWWDjMfl5WyhuAylP/LDm2hb4ymUmSymV0EFRQcmM8BypwjhWP8F7x4i
# O88d+9GZ9MQmNh3jSDohhXXgf8rONEAyfCPVmJzM7ytsurZ9xocbuEL7+P7EkIwo
# OuMFlTF2G/zuqx1E+wANslpPqPpb8PC56BQxgJCI1LOF5lk3AePJ78OL3aw/Ndlk
# vdVl3VgBSPX4Nawt3UgUofuPn/cp9vwKKBwuIWQEFZ837GXXITshd2Mfs6oYfxXE
# tmj2SBGEhxVs7xERuWGb0cK6afy7naKkbZI2v1UqsxuZt94rn/ey2ynvunlx0R6/
# b6nNkC1rOTAfWlpsAj/QlzyM6uYTSxYZC2YWzLbbRl0lRtSz+4TdpUU/oAZSB+Y+
# s12Rqmgzi7RVxNcI2lm//sCEm6A63nCJCgYtM+LLe9pTshl/Wf8OOuPQRiA+stTs
# g89BOG9tblaz2kfeOkYf5hdH8phAbuOuDQfr6s5Ya6W+vZz6E0Zsenzi0OtMf5RC
# a2hADYVgUxD+grC8EptfWeVAWgYCaQFheNN/ZGNQMkk78V63yoPBffJEAu+B5xlT
# PYoijUdo9NXovJmoGXj6R8Tgso+QPaAGHKxCbHa1QL9ASMF3Os1jrogCHGiykfp1
# dKGnmA5wJT6Nx7BedlSDsAkCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBSY8aUrsUaz
# hxByH79dhiQCL/7QdjAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAT7ss/ZAZ0bTa
# FsrsiJYd//LQ6ImKb9JZSKiRw9xs8hwk5Y/7zign9gGtweRChC2lJ8GVRHgrFkBx
# ACjuuPprSz/UYX7n522JKcudnWuIeE1p30BZrqPTOnscD98DZi6WNTAymnaS7it5
# qAgNInreAJbTU2cAosJoeXAHr50YgSGlmJM+cN6mYLAL6TTFMtFYJrpK9TM5Ryh5
# eZmm6UTJnGg0jt1pF/2u8PSdz3dDy7DF7KDJad2qHxZORvM3k9V8Yn3JI5YLPuLs
# o2J5s3fpXyCVgR/hq86g5zjd9bRRyyiC8iLIm/N95q6HWVsCeySetrqfsDyYWStw
# L96hy7DIyLL5ih8YFMd0AdmvTRoylmADuKwE2TQCTvPnjnLk7ypJW29t17Yya4V+
# Jlz54sBnPU7kIeYZsvUT+YKgykP1QB+p+uUdRH6e79Vaiz+iewWrIJZ4tXkDMmL2
# 1nh0j+58E1ecAYDvT6B4yFIeonxA/6Gl9Xs7JLciPCIC6hGdliiEBpyYeUF0ohZF
# n7NKQu80IZ0jd511WA2bq6x9aUq/zFyf8Egw+dunUj1KtNoWpq7VuJqapckYsmvm
# mYHZXCjK1Eus7V1I+aXjrBYuqyM9QpeFZU4U01YG15uWwUCaj0uZlah/RGSYMd84
# y9DCqOpfeKE6PLMk7hLnhvcOQrnxP6kwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo2RjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUATkEpJXOaqI2wfqBsw4NLVwqYqqqggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOurZ6QwIhgPMjAyNTA0MTcxMTQyMjhaGA8yMDI1MDQxODExNDIyOFowdzA9
# BgorBgEEAYRZCgQBMS8wLTAKAgUA66tnpAIBADAKAgEAAgIG8AIB/zAHAgEAAgIS
# hDAKAgUA66y5JAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAow
# CAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQBjjTLynZjp
# 038rRvYvDntm3aElN/lOcr3vGfEW1V05EYrrKp5yGyCSIP8ARvMNfoxZEtsfWE9e
# jlp0qgSdQ0E3Gsa8+UQ6RucyUGzttAtQQhOI7OY1buuhz7albaSmiZ8gRbCjl/mq
# Oco9/FHdOV8H8AYsigKKE9X4aVzvsmEEOwg2sSBoT9ayIOwR0ZId2e+E607wwlTo
# zTRzrPExOWg5ixQXgXmOPNRfboxeW9zlZgkbgKp0YIBheYXnwEdgLp4i+J7uo/nE
# uzH4KsOGjcKpJq0RSvWq3W369/uipGiQBensTyMcNth82sO/U0bP6NHnLOizy9CJ
# k7mzdOV3bhZ9MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAH8GKCvzGlahzoAAQAAAfwwDQYJYIZIAWUDBAIBBQCgggFKMBoG
# CSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgauU9qvtx
# 3T+sYj0vtgUZYRWaEvE7/opsXUAZzurO7bAwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
# MIHkMIG9BCCVQq+Qu+/h/BOVP4wweUwbHuCUhh+T7hq3d5MCaNEtYjCBmDCBgKR+
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB/Bigr8xpWoc6AAEA
# AAH8MCIEIJo/7+Vrzx49svpKYT90nuI7QT26ZgXrdEHavo4d/+LOMA0GCSqGSIb3
# DQEBCwUABIICAHqt3C+FmqyVyhEYvowgDAtIpw106arHNsoSB1Bb7NObMZ3cbDP0
# cFc1naGx5R6YnmNXMjXAyw99T2AUyYYhGyxpdCdnBPz+cPryyHjGPWM0qb4LSoFF
# 9Et0a1e5efxuBZJJzsuITAoXmIfopvWX8gQSb7rNtm/lu1foQX5dbZnePpHRtQMS
# ZTHbuTBg0wbWFMno6PJb2hnwz6A2NFc2B+KB3nImttC0eU3BrmgV2FBHRrbIfZ9x
# Ry825fMD1zF0NFfxHJ33ObF9gybLrGYHW+HGfdKexRJAHM2XyXyKCeLp14RMr0Z5
# cD2SqG9A+pwnh8O+wz7o8VEaZPLSXPop40ya18f8BhOdvb8EOvuRL/FPSeQnShw4
# 670/ZHi6AAC0D/nPodDK7ZrLcwYQ8X7ESN+iZj7St41ggBf5pc0gRGQvoZa75aC8
# wB4JHVBaaystNeci+y02E7IsAEWIYvU/sk8V3vWjznlXHZVbLpV8owRRd3UPY9x+
# 8X2wT2q298GgTZn1A/Cyv92cBD6mCgvHoGU6kwH2tj8QpEqA8EYBO0Zs/CNQxery
# VLnjEHml4StdpRe5luH/7n0pphf9Mt7YBlsOphqfDHayE98gf34VVwydJLEM+MG0
# oBFFuZTBn0tn45VT+HQhkU955oyOBS+Ei2nXgt87/CsXSTDakhD8muBm
# SIG # End signature block
